version: 2

defaults: &defaults
  working_directory: ~/repo
  environment:
    LC_ALL: C.UTF-8

install_hex_rebar: &install_hex_rebar
  run:
    name: Install hex and rebar
    command: |
      mix local.hex --force
      mix local.rebar --force

install_system_deps: &install_system_deps
  run:
    name: Install system dependencies
    command: |
      apk add build-base linux-headers

jobs:
  build_elixir_1_14_otp_25:
    docker:
      - image: hexpm/elixir:1.14.5-erlang-25.3.2.8-alpine-3.18.4
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
      - run: mix deps.unlock --check-unused
      - run: mix docs
      - run: mix hex.build
      - run: MIX_ENV=test mix credo -a
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_13_otp_25:
    docker:
      - image: hexpm/elixir:1.13.4-erlang-25.3.2.8-alpine-3.18.4
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
      - run: mix deps.unlock --check-unused
      - run: mix docs
      - run: mix hex.build
      - run: MIX_ENV=test mix credo -a
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

  build_elixir_1_13_otp_24:
    docker:
      - image: hexpm/elixir:1.13.1-erlang-24.0.2-alpine-3.13.3
    <<: *defaults
    steps:
      - checkout
      - <<: *install_hex_rebar
      - <<: *install_system_deps
      - restore_cache:
          keys:
            - v1-mix-cache-{{ checksum "mix.lock" }}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - run: mix test
      - run: mix deps.unlock --check-unused
      - run: mix docs
      - run: mix hex.build
      - run: MIX_ENV=test mix credo -a
      - run: mix dialyzer
      - save_cache:
          key: v1-mix-cache-{{ checksum "mix.lock" }}
          paths:
            - _build
            - deps

workflows:
  version: 2
  build_test:
    jobs:
      - build_elixir_1_14_otp_25
      - build_elixir_1_13_otp_25
      - build_elixir_1_13_otp_24
